db.ventas.drop();
db.ventas.insertMany([
    {
        id:01,
        item:[
            {
                name:"Sakura Blue",
                soldPrice:259.99,
                companyPrice:90,
                soldUnits:120,
                features:{
                    switch:"blue",
                    porcentage:60,
                    weight:1200,
                    type:"ANSI"
                }
            },
            {
                name:"Sakura Brown",
                soldPrice:230,
                companyPrice:79.99,
                soldUnits:200,
                features:{
                    switch:"brown",
                    porcentage:60,
                    weight:1200,
                    type:"ANSI"
                }
            },
            {
                name:"Sakura Red",
                soldPrice:199.99,
                companyPrice:69.99,
                soldUnits:350,
                features:{
                    switch:"red",
                    porcentage:60,
                    weight:1200,
                    type:"ANSI"
                }
            },
        ],
        dateOfSale: new Date("2006-12-16"),
        particular:false,
        client:{
            name:"Amazon Inc",
            CIF: "B34187888"
        },
        seller:"Maria"
    },
    {
        id:02,
        item:[
            {
                name:"Crane",
                soldPrice:459.99,
                companyPrice:300,
                soldUnits:10,
                features:{
                    switch:"blue",
                    porcentage:80,
                    weight:1400,
                    type:"ISO"
                }
            },
            {
                name:"Candy",
                soldPrice:180.99,
                companyPrice:90,
                soldUnits:5,
                features:{
                    switch:"silver",
                    porcentage:110,
                    weight:2200,
                    type:"ANSI"
                }
            },
            {
                name:"BamBoo",
                soldPrice:199.99,
                companyPrice:69.99,
                soldUnits:2,
                features:{
                    switch:"black",
                    porcentage:100,
                    weight:1100,
                    type:"ISO"
                }
            },
        ],
        dateOfSale: new Date("2007-06-11"),
        particular:false,
        client:{
            name:"Beta Zone",
            CIF:"J96642309"
        },
        seller:"Antonio"
    },
    {
        id:03,
        item:[
            {
                name:"Koi",
                soldPrice:459.99,
                companyPrice:300,
                soldUnits:1,
                features:{
                    switch:"blue",
                    porcentage:80,
                    weight:1400,
                    type:"ISO"
                }
            }
        ],
        dateOfSale: new Date("2010-08-04"),
        particular:true,
        client:{
            name:"Antonio de la Torre Gomez",
            NIF:"44054310H"
        },
        seller:"Antonio"
    },
    {
        id:04,
        item:[
            {
                name:"Candy",
                soldPrice:239.99,
                companyPrice:100,
                soldUnits:5,
                features:{
                    switch:"red",
                    porcentage:60,
                    weight:1010,
                    type:"ISO"
                }
            }
        ],
        dateOfSale: new Date("2020-05-05"),
        particular:true,
        client:{
            name:"Juana Garcia Menacho",
            NIF:"44043510M"
        },
        seller:"Juan"
    },
    {
        id:05,
        item:[
            {
                name:" Coastline",
                soldPrice:315.99,
                companyPrice:223,
                soldUnits:3,
                features:{
                    switch:"brown",
                    porcentage:60,
                    weight:959,
                    type:"ANSI"
                },
            },
            {
                name:"BamBoo",
                soldPrice:199.99,
                companyPrice:69.99,
                soldUnits:2,
                features:{
                    switch:"black",
                    porcentage:100,
                    weight:1100,
                    type:"ISO"
                },
            }
        ],
        dateOfSale: new Date("2014-11-11"),
        particular:true,
        client:{
            name:"Agustin Colon Saborido",
            NIF:"49789495S"
        },
        seller:"Juan"
    },
    {
        id:06,
        item:[
            {
                name:" Coastline",
                soldPrice:315.99,
                companyPrice:223,
                soldUnits:35,
                features:{
                    switch:"brown",
                    porcentage:60,
                    weight:959,
                    type:"ANSI"
                }
            },
            {
                name:"Koi",
                soldPrice:459.99,
                companyPrice:300,
                soldUnits:20,
                features:{
                    switch:"blue",
                    porcentage:80,
                    weight:1400,
                    type:"ISO"
                }
            },
            {
                name:"BamBoo",
                soldPrice:199.99,
                companyPrice:69.99,
                soldUnits:100,
                features:{
                    switch:"black",
                    porcentage:100,
                    weight:1100,
                    type:"ISO"
                }
            },
            {
                name:"Sakura Blue",
                soldPrice:259.99,
                companyPrice:90,
                soldUnits:120,
                features:{
                    switch:"blue",
                    porcentage:60,
                    weight:1200,
                    type:"ANSI"
                }
            }
        ],
        dateOfSale: new Date("2017-02-09"),
        particular:false,
        client:{
            name:"PCcomponentes",
            NIF:"J94652309"
        },
        seller:"Maria"
    },
    {
        id:07,
        item:[
            {
                name:"Sakura Brown",
                soldPrice:230,
                companyPrice:79.99,
                soldUnits:100,
                features:{
                    switch:"blue",
                    porcentage:60,
                    weight:1200,
                    type:"ISO"
                }
            },
            {
                name:"BamBoo",
                soldPrice:199.99,
                companyPrice:69.99,
                soldUnits:35,
                features:{
                    switch:"black",
                    porcentage:100,
                    weight:1100,
                    type:"ISO"
                },
            },
            {
                name:"Sakura Red",
                soldPrice:199.99,
                companyPrice:69.99,
                soldUnits:100,
                features:{
                    switch:"red",
                    porcentage:60,
                    weight:1200,
                    type:"ANSI"
                }
            },
        ],
        dateOfSale: new Date("20012-11-11"),
        particular:false,
        client:{
            name:"PC_Box",
            NIF:"J93872309"
        },
        seller:"Juan"
    },
    {
        id:08,
        item:[
            {
                name:"Koi",
                soldPrice:459.99,
                companyPrice:300,
                soldUnits:2,
                features:{
                    switch:"blue",
                    porcentage:80,
                    weight:1400,
                    type:"ISO"
                }
            }
        ],
        dateOfSale: new Date("2020-06-22"),
        particular:true,
        client:{
            name:"Raul Gómez de la Torre",
            NIF:"44563510S"
        },
        seller:"Juan"
    },
    {
        id:09,
        item:[
            {
                name:"Sakura Red",
                soldPrice:199.99,
                companyPrice:69.99,
                soldUnits:100,
                features:{
                    switch:"red",
                    porcentage:60,
                    weight:1200,
                    type:"ANSI"
                }
            }
        ],
        dateOfSale: new Date("2019-01-11"),
        particular:true,
        client:{
            name:"Jordi Wild",
            NIF:"44578590A"
        },
        seller:"Juan"
    },
    {
        id:10,
        item:[
            {
                name:"Koi",
                soldPrice:459.99,
                companyPrice:300,
                soldUnits:100,
                features:{
                    switch:"blue",
                    porcentage:80,
                    weight:1400,
                    type:"ISO"
                }
            },
            {
                name:"Sakura Red",
                soldPrice:199.99,
                companyPrice:69.99,
                soldUnits:90,
                features:{
                    switch:"red",
                    porcentage:60,
                    weight:1200,
                    type:"ANSI"
                }
            },
            {
                name:"Crane",
                soldPrice:459.99,
                companyPrice:300,
                soldUnits:45,
                features:{
                    switch:"blue",
                    porcentage:80,
                    weight:1400,
                    type:"ISO"
                }
            },
        ],
        dateOfSale: new Date("2018-09-04"),
        particular:false,
        client:{
            name:"Francisco Perez Ruiz",
            NIF:"44374310H"
        },
        seller:"Antonio"
    },

])


